apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: antimatter
  namespace: antimatter-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: antimatter
  serviceName: "anti-svc"
  template:
    metadata:
      labels:
        app: antimatter
        appDns: antimatter
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: srujun/antimatter:latest
        name: antimatter
        ports:
        - name: peer
          containerPort: 9991
        - name: client
          containerPort: 9995
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: antimatter-client
  namespace: antimatter-ns
  labels:
    app: antimatter-client
    appDns: antimatter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antimatter-client
  template:
    metadata:
      labels:
        app: antimatter-client
        appDns: antimatter
    spec:
      containers:
      - image: srujun/antimatter-client:latest
        name: antimatter-client
---
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: anti-svc
  namespace: antimatter-ns
spec:
  ports:
  - name: peer
    port: 9991
  - name: client
    port: 9995
  # [podname].antimatter-svc.antimatter-ns.svc.cluster.local
  clusterIP: None
  selector:
    appDns: antimatter